repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
  - repo: local
    hooks:
      - id: codespell
        name: codespell
        language: system
        entry: uv run --frozen codespell
      - id: ruff-check
        name: ruff check
        language: system
        entry: uv run --frozen ruff check --force-exclude
        types_or: [python, pyi]
      - id: ruff-format
        name: ruff format
        language: system
        entry: uv run --frozen ruff format --force-exclude
        types_or: [python, pyi]
      - id: ty-check
        name: ty check
        language: system
        entry: uv run --frozen ty check src tests
        pass_filenames: false
        args: [--python=.venv/]
